// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function str(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("ExportTabs");

function make(tabsData, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("button", {
                          onClick: (function () {
                              return Curry._1(_self[/* send */3], /* ExportTabs */0);
                            })
                        }, _self[/* state */1][/* instructions */0]);
            }),
          /* initialState */(function () {
              return /* record */[/* instructions */"Click here to download your tabs"];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, _$1) {
              var downloadTabs = (
      function (tabsArr) {
        let jsonData = JSON.stringify(tabsArr)
        var element = document.createElement("a");
        var file = new Blob([jsonData], {type: 'application/json'});
        element.href = URL.createObjectURL(file);
        element.download = "mySavedTabs.json";
        element.click();
      }
      );
              Curry._1(downloadTabs, tabsData);
              return /* NoUpdate */0;
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.tabsData, /* array */[]);
      }));

exports.str = str;
exports.component = component;
exports.make = make;
exports.jsComponent = jsComponent;
/* component Not a pure module */
